##########################################################################
# Rules
##########################################################################
all:
	make -f makefile.bh
	make -f makefile.bg	
	make -f makefile.rg
	
clean:
	make -f makefile.bh clean
	make -f makefile.bg clean	
	make -f makefile.rg clean	
